source 'https://rubygems.org'

ruby '>= 3.2'

gem 'rails', '~> 8.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'jbuilder', '~> 2.12'
gem 'devise', '~> 4.9'
gem 'devise-jwt', '~> 0.11'
gem 'rack-cors', '~> 2.0'
gem 'bootsnap', require: false

group :development, :test do
  gem 'rspec-rails', '~> 7.0'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.4'
  gem 'pry-rails', '~> 0.3'
end

group :development do
  gem 'rubocop-rails-omakase', require: false
end
