use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIConfig {
    pub version: String,
    pub orbs: HashMap<String, String>,
    pub executors: HashMap<String, CircleCIExecutor>,
    pub commands: HashMap<String, CircleCICommand>,
    pub jobs: HashMap<String, CircleCIJob>,
    pub workflows: HashMap<String, CircleCIWorkflow>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIExecutor {
    pub docker: Vec<CircleCIDockerImage>,
    pub resource_class: Option<String>,
    pub working_directory: Option<String>,
    pub environment: Option<HashMap<String, String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIDockerImage {
    pub image: String,
    pub auth: Option<CircleCIDockerAuth>,
    pub environment: Option<HashMap<String, String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIDockerAuth {
    pub username: String,
    pub password: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCICommand {
    pub description: String,
    pub parameters: Option<HashMap<String, CircleCIParameter>>,
    pub steps: Vec<CircleCIStep>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIParameter {
    pub description: String,
    pub param_type: String,
    pub default: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIJob {
    pub executor: Option<String>,
    pub docker: Option<Vec<CircleCIDockerImage>>,
    pub parallelism: Option<u32>,
    pub resource_class: Option<String>,
    pub working_directory: Option<String>,
    pub environment: Option<HashMap<String, String>>,
    pub steps: Vec<CircleCIStep>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIStep {
    pub name: Option<String>,
    pub run: Option<String>,
    pub checkout: Option<bool>,
    pub restore_cache: Option<CircleCICache>,
    pub save_cache: Option<CircleCICache>,
    pub persist_to_workspace: Option<CircleCIWorkspace>,
    pub attach_workspace: Option<CircleCIWorkspace>,
    pub store_artifacts: Option<CircleCIArtifact>,
    pub store_test_results: Option<CircleCITestResults>,
    pub setup_remote_docker: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCICache {
    pub key: String,
    pub paths: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIWorkspace {
    pub root: String,
    pub paths: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIArtifact {
    pub path: String,
    pub destination: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCITestResults {
    pub path: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIWorkflow {
    pub jobs: Vec<CircleCIWorkflowJob>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIWorkflowJob {
    pub name: String,
    pub requires: Vec<String>,
    pub filters: Option<CircleCIWorkflowFilters>,
    pub matrix: Option<CircleCIMatrix>,
    pub context: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIWorkflowFilters {
    pub branches: Option<CircleCIBranchFilter>,
    pub tags: Option<CircleCITagFilter>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIBranchFilter {
    pub only: Vec<String>,
    pub ignore: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCITagFilter {
    pub only: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircleCIMatrix {
    pub parameters: HashMap<String, Vec<String>>,
}

impl CircleCIConfig {
    pub fn new() -> Self {
        Self {
            version: "2.1".into(),
            orbs: HashMap::from([
                ("node".into(), "circleci/node@5".into()),
                ("aws-cli".into(), "circleci/aws-cli@5".into()),
                ("gcp-cli".into(), "circleci/gcp-cli@3".into()),
                ("azure-cli".into(), "circleci/azure-cli@2".into()),
            ]),
            executors: HashMap::new(),
            commands: HashMap::new(),
            jobs: HashMap::new(),
            workflows: HashMap::new(),
        }
    }

    pub fn generate(&self) -> String {
        let mut out = String::from("# Klyron CircleCI Configuration\n# Generated by klyron_deploy_system\n\n");
        out.push_str(&format!("version: {}\n\n", self.version));

        if !self.orbs.is_empty() {
            out.push_str("orbs:\n");
            for (name, version) in &self.orbs {
                out.push_str(&format!("  {name}: {version}\n"));
            }
            out.push('\n');
        }

        if !self.executors.is_empty() {
            out.push_str("executors:\n");
            for (name, exec) in &self.executors {
                out.push_str(&format!("  {name}:\n"));
                out.push_str("    docker:\n");
                for img in &exec.docker {
                    out.push_str(&format!("      - image: {}\n", img.image));
                }
                if let Some(ref rc) = exec.resource_class {
                    out.push_str(&format!("    resource_class: {rc}\n"));
                }
            }
            out.push('\n');
        }

        if !self.jobs.is_empty() {
            out.push_str("jobs:\n");
            for (name, job) in &self.jobs {
                out.push_str(&format!("  {name}:\n"));
                if let Some(ref docker) = job.docker {
                    out.push_str("    docker:\n");
                    for img in docker {
                        out.push_str(&format!("      - image: {}\n", img.image));
                    }
                }
                if let Some(parallelism) = job.parallelism {
                    out.push_str(&format!("    parallelism: {parallelism}\n"));
                }
                if let Some(ref rc) = job.resource_class {
                    out.push_str(&format!("    resource_class: {rc}\n"));
                }
                if let Some(ref wd) = job.working_directory {
                    out.push_str(&format!("    working_directory: {wd}\n"));
                }
                if let Some(ref env) = job.environment {
                    out.push_str("    environment:\n");
                    for (k, v) in env {
                        out.push_str(&format!("      {k}: {v}\n"));
                    }
                }
                out.push_str("    steps:\n");
                for step in &job.steps {
                    Self::write_step(&mut out, step, 6);
                }
                out.push('\n');
            }
        }

        if !self.workflows.is_empty() {
            out.push_str("workflows:\n");
            for (name, workflow) in &self.workflows {
                out.push_str(&format!("  {name}:\n"));
                out.push_str("    jobs:\n");
                for wj in &workflow.jobs {
                    out.push_str(&format!("      - {}\n", wj.name));
                    if !wj.requires.is_empty() {
                        out.push_str(&format!("          requires:\n"));
                        for r in &wj.requires {
                            out.push_str(&format!("            - {r}\n"));
                        }
                    }
                    if let Some(ref filters) = wj.filters {
                        out.push_str("          filters:\n");
                        if let Some(ref branches) = filters.branches {
                            out.push_str("            branches:\n");
                            if !branches.only.is_empty() {
                                out.push_str(&format!("              only: {}\n", yaml_circle_list(&branches.only)));
                            }
                            if !branches.ignore.is_empty() {
                                out.push_str(&format!("              ignore: {}\n", yaml_circle_list(&branches.ignore)));
                            }
                        }
                        if let Some(ref tags) = filters.tags {
                            out.push_str("            tags:\n");
                            out.push_str(&format!("              only: {}\n", yaml_circle_list(&tags.only)));
                        }
                    }
                    if let Some(ref matrix) = wj.matrix {
                        out.push_str("          matrix:\n");
                        out.push_str("            parameters:\n");
                        for (k, v) in &matrix.parameters {
                            out.push_str(&format!("              {k}: {}\n", yaml_circle_list(v)));
                        }
                    }
                    if let Some(ref context) = wj.context {
                        out.push_str(&format!("          context: {}\n", yaml_circle_list(context)));
                    }
                }
            }
        }
        out
    }

    fn write_step(out: &mut String, step: &CircleCIStep, indent: usize) {
        let pad = " ".repeat(indent);
        if step.checkout == Some(true) {
            out.push_str(&format!("{pad}- checkout\n"));
        }
        if let Some(ref run) = step.run {
            if run.contains('\n') {
                out.push_str(&format!("{pad}- run:\n{pad}    command: |\n"));
                for line in run.lines() {
                    out.push_str(&format!("{pad}      {line}\n"));
                }
            } else {
                out.push_str(&format!("{pad}- run: {run}\n"));
            }
            if let Some(ref name) = step.name {
                out.push_str(&format!("{pad}    name: \"{name}\"\n"));
            }
        }
        if let Some(ref cache) = step.restore_cache {
            out.push_str(&format!("{pad}- restore_cache:\n{pad}    key: {}\n", cache.key));
        }
        if let Some(ref cache) = step.save_cache {
            out.push_str(&format!("{pad}- save_cache:\n{pad}    key: {}\n{pad}    paths:\n", cache.key));
            for p in &cache.paths {
                out.push_str(&format!("{pad}      - {p}\n"));
            }
        }
        if let Some(ref ws) = step.persist_to_workspace {
            out.push_str(&format!("{pad}- persist_to_workspace:\n{pad}    root: {}\n{pad}    paths:\n", ws.root));
            for p in &ws.paths {
                out.push_str(&format!("{pad}      - {p}\n"));
            }
        }
        if let Some(ref ws) = step.attach_workspace {
            out.push_str(&format!("{pad}- attach_workspace:\n{pad}    at: {}\n", ws.root));
        }
        if let Some(ref artifact) = step.store_artifacts {
            out.push_str(&format!("{pad}- store_artifacts:\n{pad}    path: {}\n", artifact.path));
            if let Some(ref dest) = artifact.destination {
                out.push_str(&format!("{pad}    destination: {dest}\n"));
            }
        }
        if let Some(ref test_results) = step.store_test_results {
            out.push_str(&format!("{pad}- store_test_results:\n{pad}    path: {}\n", test_results.path));
        }
        if step.setup_remote_docker == Some(true) {
            out.push_str(&format!("{pad}- setup_remote_docker\n"));
        }
    }

    pub fn generate_circleci_config() -> Self {
        let mut config = Self::new();

        config.executors.insert(
            "rust-executor".into(),
            CircleCIExecutor {
                docker: vec![CircleCIDockerImage {
                    image: "cimg/rust:1.78".into(),
                    auth: None,
                    environment: None,
                }],
                resource_class: Some("medium".into()),
                working_directory: None,
                environment: Some(HashMap::from([("CARGO_TERM_COLOR".into(), "always".into())])),
            },
        );

        config.jobs.insert(
            "test".into(),
            CircleCIJob {
                executor: Some("rust-executor".into()),
                docker: None,
                parallelism: Some(4),
                resource_class: None,
                working_directory: None,
                environment: None,
                steps: vec![
                    CircleCIStep {
                        name: None,
                        run: None,
                        checkout: Some(true),
                        restore_cache: Some(CircleCICache {
                            key: "cargo-cache-{{ checksum \"Cargo.lock\" }}".into(),
                            paths: vec!["~/.cargo/registry".into(), "~/.cargo/git".into()],
                        }),
                        save_cache: None,
                        persist_to_workspace: None,
                        attach_workspace: None,
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: None,
                    },
                    CircleCIStep {
                        name: Some("Run cargo tests".into()),
                        run: Some("cargo test --all-targets -- --test-threads=$(nproc)".into()),
                        checkout: None,
                        restore_cache: None,
                        save_cache: None,
                        persist_to_workspace: None,
                        attach_workspace: None,
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: None,
                    },
                    CircleCIStep {
                        name: Some("Run clippy".into()),
                        run: Some("cargo clippy --all-targets -- -D warnings".into()),
                        checkout: None,
                        restore_cache: None,
                        save_cache: None,
                        persist_to_workspace: None,
                        attach_workspace: None,
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: None,
                    },
                    CircleCIStep {
                        name: None,
                        run: None,
                        checkout: None,
                        restore_cache: None,
                        save_cache: Some(CircleCICache {
                            key: "cargo-cache-{{ checksum \"Cargo.lock\" }}".into(),
                            paths: vec!["~/.cargo/registry".into(), "~/.cargo/git".into(), "target".into()],
                        }),
                        persist_to_workspace: Some(CircleCIWorkspace {
                            root: ".".into(),
                            paths: vec!["target".into()],
                        }),
                        attach_workspace: None,
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: None,
                    },
                ],
            },
        );

        config.jobs.insert(
            "build".into(),
            CircleCIJob {
                executor: Some("rust-executor".into()),
                docker: None,
                parallelism: None,
                resource_class: Some("medium".into()),
                working_directory: None,
                environment: None,
                steps: vec![
                    CircleCIStep {
                        name: None,
                        run: None,
                        checkout: Some(true),
                        restore_cache: Some(CircleCICache {
                            key: "cargo-cache-{{ checksum \"Cargo.lock\" }}".into(),
                            paths: vec!["~/.cargo/registry".into(), "~/.cargo/git".into()],
                        }),
                        save_cache: None,
                        persist_to_workspace: None,
                        attach_workspace: None,
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: None,
                    },
                    CircleCIStep {
                        name: Some("Attach workspace".into()),
                        run: None,
                        checkout: None,
                        restore_cache: None,
                        save_cache: None,
                        persist_to_workspace: None,
                        attach_workspace: Some(CircleCIWorkspace {
                            root: ".".into(),
                            paths: vec!["target".into()],
                        }),
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: None,
                    },
                    CircleCIStep {
                        name: Some("Build release".into()),
                        run: Some("cargo build --release --locked".into()),
                        checkout: None,
                        restore_cache: None,
                        save_cache: None,
                        persist_to_workspace: None,
                        attach_workspace: None,
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: None,
                    },
                    CircleCIStep {
                        name: None,
                        run: None,
                        checkout: None,
                        restore_cache: None,
                        save_cache: Some(CircleCICache {
                            key: "cargo-cache-{{ checksum \"Cargo.lock\" }}".into(),
                            paths: vec!["~/.cargo/registry".into(), "~/.cargo/git".into(), "target".into()],
                        }),
                        persist_to_workspace: Some(CircleCIWorkspace {
                            root: ".".into(),
                            paths: vec!["target/release/klyron".into()],
                        }),
                        attach_workspace: None,
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: None,
                    },
                ],
            },
        );

        config.jobs.insert(
            "deploy".into(),
            CircleCIJob {
                executor: Some("rust-executor".into()),
                docker: None,
                parallelism: None,
                resource_class: Some("medium".into()),
                working_directory: None,
                environment: None,
                steps: vec![
                    CircleCIStep {
                        name: None,
                        run: None,
                        checkout: Some(true),
                        restore_cache: None,
                        save_cache: None,
                        persist_to_workspace: None,
                        attach_workspace: Some(CircleCIWorkspace {
                            root: ".".into(),
                            paths: vec!["target/release/klyron".into()],
                        }),
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: Some(true),
                    },
                    CircleCIStep {
                        name: Some("Deploy application".into()),
                        run: Some("cargo run -- deploy --env production".into()),
                        checkout: None,
                        restore_cache: None,
                        save_cache: None,
                        persist_to_workspace: None,
                        attach_workspace: None,
                        store_artifacts: None,
                        store_test_results: None,
                        setup_remote_docker: None,
                    },
                ],
            },
        );

        config.workflows.insert(
            "klyron-workflow".into(),
            CircleCIWorkflow {
                jobs: vec![
                    CircleCIWorkflowJob {
                        name: "test".into(),
                        requires: vec![],
                        filters: Some(CircleCIWorkflowFilters {
                            branches: Some(CircleCIBranchFilter {
                                only: vec!["main".into(), "master".into(), "develop".into(), "/feature-.*/".into()],
                                ignore: vec![],
                            }),
                            tags: None,
                        }),
                        matrix: None,
                        context: None,
                    },
                    CircleCIWorkflowJob {
                        name: "build".into(),
                        requires: vec!["test".into()],
                        filters: Some(CircleCIWorkflowFilters {
                            branches: Some(CircleCIBranchFilter {
                                only: vec!["main".into(), "master".into()],
                                ignore: vec![],
                            }),
                            tags: Some(CircleCITagFilter {
                                only: vec!["/v.*/".into()],
                            }),
                        }),
                        matrix: None,
                        context: None,
                    },
                    CircleCIWorkflowJob {
                        name: "deploy".into(),
                        requires: vec!["build".into()],
                        filters: Some(CircleCIWorkflowFilters {
                            branches: Some(CircleCIBranchFilter {
                                only: vec!["main".into(), "master".into()],
                                ignore: vec![],
                            }),
                            tags: None,
                        }),
                        matrix: None,
                        context: Some(vec!["klyron-deploy".into()]),
                    },
                ],
            },
        );

        config
    }

    pub fn write<R: AsRef<Path>>(output_dir: R) -> Result<(), String> {
        let config = Self::generate_circleci_config();
        let yaml = config.generate();
        let circle_dir = output_dir.as_ref().join(".circleci");
        fs::create_dir_all(&circle_dir).map_err(|e| format!("Cannot create .circleci directory: {e}"))?;
        fs::write(circle_dir.join("config.yml"), &yaml)
            .map_err(|e| format!("Cannot write config.yml: {e}"))
    }
}

impl Default for CircleCIConfig {
    fn default() -> Self {
        Self::new()
    }
}

fn yaml_circle_list(items: &[String]) -> String {
    let vals: Vec<String> = items.iter().map(|s| format!("\"{s}\"")).collect();
    format!("[{}]", vals.join(", "))
}
