use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitHubWorkflow {
    pub name: String,
    pub on: GitHubTrigger,
    pub env: HashMap<String, String>,
    pub jobs: HashMap<String, GitHubJob>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitHubTrigger {
    pub push: GitHubBranchFilter,
    pub pull_request: GitHubBranchFilter,
    pub workflow_dispatch: Option<WorkflowDispatch>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitHubBranchFilter {
    pub branches: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowDispatch {
    pub inputs: HashMap<String, DispatchInput>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DispatchInput {
    pub description: String,
    pub required: bool,
    #[serde(rename = "type")]
    pub input_type: String,
    pub default: String,
    pub options: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitHubJob {
    pub runs_on: String,
    pub needs: Vec<String>,
    pub if_: Option<String>,
    pub environment: Option<String>,
    pub permissions: Option<HashMap<String, String>>,
    pub strategy: Option<GitHubStrategy>,
    pub services: Option<HashMap<String, GitHubService>>,
    pub steps: Vec<GitHubStep>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitHubStrategy {
    pub matrix: HashMap<String, Vec<String>>,
    pub fail_fast: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitHubService {
    pub image: String,
    pub env: HashMap<String, String>,
    pub ports: Vec<String>,
    pub options: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitHubStep {
    pub name: String,
    pub uses: Option<String>,
    pub run: Option<String>,
    pub with: Option<HashMap<String, String>>,
    pub env: Option<HashMap<String, String>>,
    pub working_directory: Option<String>,
    pub continue_on_error: Option<bool>,
    pub timeout_minutes: Option<u32>,
}

impl GitHubWorkflow {
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            on: GitHubTrigger {
                push: GitHubBranchFilter {
                    branches: vec!["main".into(), "master".into(), "develop".into()],
                },
                pull_request: GitHubBranchFilter {
                    branches: vec!["main".into(), "master".into()],
                },
                workflow_dispatch: Some(WorkflowDispatch {
                    inputs: HashMap::from([
                        (
                            "environment".into(),
                            DispatchInput {
                                description: "Environment to deploy to".into(),
                                required: true,
                                input_type: "choice".into(),
                                default: "staging".into(),
                                options: vec!["dev".into(), "staging".into(), "prod".into()],
                            },
                        ),
                    ]),
                }),
            },
            env: HashMap::new(),
            jobs: HashMap::new(),
        }
    }

    fn to_yaml(&self) -> String {
        let mut out = format!("# Klyron Deploy Workflow: {}\n# Generated by klyron_deploy_system\n\n", self.name);
        out.push_str(&format!("name: {}\n\n", self.name));

        out.push_str("on:\n");
        out.push_str(&format!("  push:\n    branches: {}\n", yaml_list(&self.on.push.branches)));
        out.push_str(&format!("  pull_request:\n    branches: {}\n", yaml_list(&self.on.pull_request.branches)));
        if let Some(ref wd) = self.on.workflow_dispatch {
            out.push_str("  workflow_dispatch:\n    inputs:\n");
            for (name, input) in &wd.inputs {
                out.push_str(&format!(
                    "      {name}:\n        description: \"{}\"\n        required: {}\n        type: {}\n        default: \"{}\"\n",
                    input.description, input.required, input.input_type, input.default
                ));
            }
        }
        out.push('\n');

        if !self.env.is_empty() {
            out.push_str("env:\n");
            for (k, v) in &self.env {
                out.push_str(&format!("  {k}: {v}\n"));
            }
            out.push('\n');
        }

        out.push_str("jobs:\n");
        for (name, job) in &self.jobs {
            out.push_str(&format!("  {name}:\n"));
            out.push_str(&format!("    runs-on: {}\n", job.runs_on));

            if !job.needs.is_empty() {
                out.push_str(&format!("    needs: [{}]\n", job.needs.join(", ")));
            }
            if let Some(ref if_cond) = job.if_ {
                out.push_str(&format!("    if: {if_cond}\n"));
            }
            if let Some(ref env_name) = job.environment {
                out.push_str(&format!("    environment: {env_name}\n"));
            }
            if let Some(ref permissions) = job.permissions {
                out.push_str("    permissions:\n");
                for (k, v) in permissions {
                    out.push_str(&format!("      {k}: {v}\n"));
                }
            }
            if let Some(ref strategy) = job.strategy {
                out.push_str("    strategy:\n");
                out.push_str(&format!("      fail-fast: {}\n", strategy.fail_fast));
                out.push_str("      matrix:\n");
                for (k, v) in &strategy.matrix {
                    out.push_str(&format!("        {k}: {}\n", yaml_list(v)));
                }
            }
            if let Some(ref services) = job.services {
                out.push_str("    services:\n");
                for (name, svc) in services {
                    out.push_str(&format!("      {name}:\n"));
                    out.push_str(&format!("        image: {}\n", svc.image));
                    if !svc.env.is_empty() {
                        out.push_str("        env:\n");
                        for (k, v) in &svc.env {
                            out.push_str(&format!("          {k}: {v}\n"));
                        }
                    }
                    if !svc.ports.is_empty() {
                        out.push_str(&format!("        ports: {}\n", yaml_list(&svc.ports)));
                    }
                    if !svc.options.is_empty() {
                        out.push_str(&format!("        options: \"{}\"\n", svc.options));
                    }
                }
            }
            out.push_str("    steps:\n");
            for step in &job.steps {
                out.push_str(&format!("      - name: \"{}\"\n", step.name));
                if let Some(ref uses) = step.uses {
                    out.push_str(&format!("        uses: {uses}\n"));
                }
                if let Some(ref run) = step.run {
                    let lines: Vec<&str> = run.lines().collect();
                    if lines.len() == 1 {
                        out.push_str(&format!("        run: {}\n", lines[0]));
                    } else {
                        out.push_str("        run: |\n");
                        for line in lines {
                            out.push_str(&format!("          {line}\n"));
                        }
                    }
                }
                if let Some(ref with) = step.with {
                    out.push_str("        with:\n");
                    for (k, v) in with {
                        out.push_str(&format!("          {k}: {v}\n"));
                    }
                }
                if let Some(ref env_vars) = step.env {
                    out.push_str("        env:\n");
                    for (k, v) in env_vars {
                        out.push_str(&format!("          {k}: {v}\n"));
                    }
                }
                if let Some(ref wd) = step.working_directory {
                    out.push_str(&format!("        working-directory: {wd}\n"));
                }
                if let Some(cont) = step.continue_on_error {
                    out.push_str(&format!("        continue-on-error: {cont}\n"));
                }
                if let Some(timeout) = step.timeout_minutes {
                    out.push_str(&format!("        timeout-minutes: {timeout}\n"));
                }
            }
        }
        out
    }

    pub fn generate<R: AsRef<Path>>(output_dir: R) -> Result<(), String> {
        let workflow = Self::generate_deploy_workflow();
        let out_dir: &Path = output_dir.as_ref();
        let workflows_dir = out_dir.join(".github").join("workflows");
        fs::create_dir_all(&workflows_dir).map_err(|e| format!("Cannot create workflows directory: {e}"))?;
        let yaml = workflow.to_yaml();
        fs::write(workflows_dir.join("deploy.yml"), &yaml)
            .map_err(|e| format!("Cannot write deploy workflow: {e}"))?;
        Ok(())
    }

    pub fn generate_deploy_workflow() -> Self {
        let mut workflow = Self::new("Klyron Deploy");

        workflow.env.insert("CARGO_TERM_COLOR".into(), "always".into());

        let test_job = GitHubJob {
            runs_on: "ubuntu-latest".into(),
            needs: vec![],
            if_: None,
            environment: None,
            permissions: None,
            strategy: Some(GitHubStrategy {
                matrix: HashMap::from([("rust".into(), vec!["stable".into(), "nightly".into()])]),
                fail_fast: false,
            }),
            services: None,
            steps: vec![
                GitHubStep {
                    name: "Checkout".into(),
                    uses: Some("actions/checkout@v4".into()),
                    run: None,
                    with: None,
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Cache Cargo registry".into(),
                    uses: Some("actions/cache@v4".into()),
                    run: None,
                    with: Some(HashMap::from([
                        ("path".into(), "~/.cargo/registry".into()),
                        ("key".into(), "${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}".into()),
                        ("restore-keys".into(), "${{ runner.os }}-cargo-registry-".into()),
                    ])),
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Cache Cargo target".into(),
                    uses: Some("actions/cache@v4".into()),
                    run: None,
                    with: Some(HashMap::from([
                        ("path".into(), "target".into()),
                        ("key".into(), "${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}".into()),
                        ("restore-keys".into(), "${{ runner.os }}-cargo-target-".into()),
                    ])),
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Install Rust toolchain".into(),
                    uses: Some("dtolnay/rust-toolchain@stable".into()),
                    run: None,
                    with: Some(HashMap::from([
                        ("toolchain".into(), "${{ matrix.rust }}".into()),
                        ("components".into(), "clippy, rustfmt".into()),
                    ])),
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Cargo check".into(),
                    uses: None,
                    run: Some("cargo check --all-targets".into()),
                    with: None,
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Cargo clippy".into(),
                    uses: None,
                    run: Some("cargo clippy --all-targets -- -D warnings".into()),
                    with: None,
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Cargo test".into(),
                    uses: None,
                    run: Some("cargo test --all-targets".into()),
                    with: None,
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
            ],
        };

        let build_job = GitHubJob {
            runs_on: "ubuntu-latest".into(),
            needs: vec!["test".into()],
            if_: None,
            environment: None,
            permissions: None,
            strategy: None,
            services: None,
            steps: vec![
                GitHubStep {
                    name: "Checkout".into(),
                    uses: Some("actions/checkout@v4".into()),
                    run: None,
                    with: None,
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Build release".into(),
                    uses: None,
                    run: Some("cargo build --release --locked".into()),
                    with: None,
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Upload artifacts".into(),
                    uses: Some("actions/upload-artifact@v4".into()),
                    run: None,
                    with: Some(HashMap::from([
                        ("name".into(), "klyron-release".into()),
                        ("path".into(), "target/release/klyron".into()),
                    ])),
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
            ],
        };

        let docker_build_job = GitHubJob {
            runs_on: "ubuntu-latest".into(),
            needs: vec!["build".into()],
            if_: Some("github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'".into()),
            environment: None,
            permissions: Some(HashMap::from([
                ("contents".into(), "read".into()),
                ("packages".into(), "write".into()),
                ("id-token".into(), "write".into()),
            ])),
            strategy: None,
            services: None,
            steps: vec![
                GitHubStep {
                    name: "Checkout".into(),
                    uses: Some("actions/checkout@v4".into()),
                    run: None,
                    with: None,
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Set up Docker Buildx".into(),
                    uses: Some("docker/setup-buildx-action@v3".into()),
                    run: None,
                    with: None,
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Login to GitHub Container Registry".into(),
                    uses: Some("docker/login-action@v3".into()),
                    run: None,
                    with: Some(HashMap::from([
                        ("registry".into(), "ghcr.io".into()),
                        ("username".into(), "${{ github.actor }}".into()),
                        ("password".into(), "${{ secrets.GITHUB_TOKEN }}".into()),
                    ])),
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Build and push Docker image".into(),
                    uses: Some("docker/build-push-action@v5".into()),
                    run: None,
                    with: Some(HashMap::from([
                        ("context".into(), ".".into()),
                        ("file".into(), "./deploy/docker/Dockerfile.multi".into()),
                        ("push".into(), "true".into()),
                        ("tags".into(), "ghcr.io/${{ github.repository }}:${{ github.sha }},ghcr.io/${{ github.repository }}:latest".into()),
                        ("cache-from".into(), "type=gha".into()),
                        ("cache-to".into(), "type=gha,mode=max".into()),
                    ])),
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
            ],
        };

        let deploy_job = GitHubJob {
            runs_on: "ubuntu-latest".into(),
            needs: vec!["docker-build".into()],
            if_: Some("github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'".into()),
            environment: Some("${{ matrix.environment }}".into()),
            permissions: Some(HashMap::from([
                ("contents".into(), "read".into()),
                ("id-token".into(), "write".into()),
            ])),
            strategy: Some(GitHubStrategy {
                matrix: HashMap::from([("environment".into(), vec!["dev".into(), "staging".into(), "prod".into()])]),
                fail_fast: false,
            }),
            services: None,
            steps: vec![
                GitHubStep {
                    name: "Checkout".into(),
                    uses: Some("actions/checkout@v4".into()),
                    run: None,
                    with: None,
                    env: None,
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Configure AWS credentials".into(),
                    uses: Some("aws-actions/configure-aws-credentials@v4".into()),
                    run: None,
                    with: Some(HashMap::from([
                        ("role-to-assume".into(), "${{ secrets.AWS_ROLE_ARN }}".into()),
                        ("aws-region".into(), "${{ secrets.AWS_REGION }}".into()),
                        ("role-session-name".into(), "klyron-deploy".into()),
                    ])),
                    env: None,
                    working_directory: None,
                    continue_on_error: Some(true),
                    timeout_minutes: None,
                },
                GitHubStep {
                    name: "Deploy to ${{ matrix.environment }}".into(),
                    uses: None,
                    run: Some("cargo run -- deploy --env ${{ matrix.environment }}".into()),
                    with: None,
                    env: Some(HashMap::from([
                        ("KLYRON_ENV".into(), "${{ matrix.environment }}".into()),
                        ("AWS_REGION".into(), "${{ secrets.AWS_REGION }}".into()),
                    ])),
                    working_directory: None,
                    continue_on_error: None,
                    timeout_minutes: Some(30),
                },
            ],
        };

        workflow.jobs.insert("test".into(), test_job);
        workflow.jobs.insert("build".into(), build_job);
        workflow.jobs.insert("docker-build".into(), docker_build_job);
        workflow.jobs.insert("deploy".into(), deploy_job);
        workflow
    }
}

fn yaml_list(items: &[String]) -> String {
    let vals: Vec<String> = items.iter().map(|s| format!("{s}")).collect();
    format!("[{}]", vals.join(", "))
}
