use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitLabCIConfig {
    pub stages: Vec<String>,
    pub variables: HashMap<String, String>,
    pub cache: GitLabCache,
    pub default: GitLabDefault,
    pub jobs: HashMap<String, GitLabJob>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitLabCache {
    pub key: String,
    pub paths: Vec<String>,
    pub policy: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitLabDefault {
    pub image: String,
    pub before_script: Vec<String>,
    pub artifacts: Option<GitLabArtifacts>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitLabArtifacts {
    pub paths: Vec<String>,
    pub expire_in: String,
    pub reports: Option<HashMap<String, String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitLabJob {
    pub stage: String,
    pub image: Option<String>,
    pub needs: Vec<String>,
    pub script: Vec<String>,
    pub only: Option<HashMap<String, Vec<String>>>,
    pub except: Option<HashMap<String, Vec<String>>>,
    pub variables: Option<HashMap<String, String>>,
    pub artifacts: Option<GitLabArtifacts>,
    pub cache: Option<GitLabCache>,
    pub environment: Option<GitLabEnvironment>,
    pub services: Option<Vec<GitLabService>>,
    pub parallel: Option<u32>,
    pub allow_failure: Option<bool>,
    pub when: Option<String>,
    pub retry: Option<u32>,
    pub timeout: Option<String>,
    pub tags: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitLabEnvironment {
    pub name: String,
    pub url: String,
    pub on_stop: Option<String>,
    pub action: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitLabService {
    pub name: String,
    pub alias: Option<String>,
    pub entrypoint: Option<Vec<String>>,
    pub command: Option<Vec<String>>,
}

impl GitLabCIConfig {
    pub fn new() -> Self {
        Self {
            stages: vec!["test".into(), "build".into(), "docker".into(), "deploy".into()],
            variables: HashMap::from([
                ("CARGO_TERM_COLOR".into(), "always".into()),
                ("RUSTFLAGS".into(), "-D warnings".into()),
            ]),
            cache: GitLabCache {
                key: "$CI_COMMIT_REF_SLUG".into(),
                paths: vec![
                    "target/".into(),
                    "~/.cargo/registry/".into(),
                    "node_modules/".into(),
                ],
                policy: "pull-push".into(),
            },
            default: GitLabDefault {
                image: "rust:latest".into(),
                before_script: vec![
                    "apt-get update -qq && apt-get install -y -qq nodejs npm".into(),
                    "rustup component add clippy rustfmt".into(),
                ],
                artifacts: None,
            },
            jobs: HashMap::new(),
        }
    }

    fn to_yaml(&self) -> String {
        let mut out = String::from("# Klyron GitLab CI Configuration\n# Generated by klyron_deploy_system\n\n");

        out.push_str(&format!("stages: {}\n\n", yaml_gitlab_list(&self.stages)));

        if !self.variables.is_empty() {
            out.push_str("variables:\n");
            for (k, v) in &self.variables {
                out.push_str(&format!("  {k}: \"{v}\"\n"));
            }
            out.push('\n');
        }

        out.push_str("default:\n");
        out.push_str(&format!("  image: {}\n", self.default.image));
        if !self.default.before_script.is_empty() {
            out.push_str("  before_script:\n");
            for s in &self.default.before_script {
                out.push_str(&format!("    - {s}\n"));
            }
        }
        out.push('\n');

        out.push_str(&format!(
            "cache:\n  key: {}\n  paths:\n",
            self.cache.key
        ));
        for p in &self.cache.paths {
            out.push_str(&format!("    - {p}\n"));
        }
        out.push_str(&format!("  policy: {}\n\n", self.cache.policy));

        for (name, job) in &self.jobs {
            out.push_str(&format!("{name}:\n"));
            out.push_str(&format!("  stage: {}\n", job.stage));
            if let Some(ref image) = job.image {
                out.push_str(&format!("  image: {image}\n"));
            }
            if !job.needs.is_empty() {
                out.push_str(&format!("  needs: {}\n", yaml_gitlab_list(&job.needs)));
            }
            if let Some(ref only) = job.only {
                out.push_str("  only:\n");
                for (k, v) in only {
                    out.push_str(&format!("    {k}: {}\n", yaml_gitlab_list(v)));
                }
            }
            if let Some(ref except) = job.except {
                out.push_str("  except:\n");
                for (k, v) in except {
                    out.push_str(&format!("    {k}: {}\n", yaml_gitlab_list(v)));
                }
            }
            if let Some(ref vars) = job.variables {
                out.push_str("  variables:\n");
                for (k, v) in vars {
                    out.push_str(&format!("    {k}: \"{v}\"\n"));
                }
            }
            if let Some(ref env) = job.environment {
                out.push_str(&format!("  environment:\n    name: {}\n    url: {}\n", env.name, env.url));
                if let Some(ref on_stop) = env.on_stop {
                    out.push_str(&format!("    on_stop: {on_stop}\n"));
                }
                if let Some(ref action) = env.action {
                    out.push_str(&format!("    action: {action}\n"));
                }
            }
            if let Some(ref services) = job.services {
                out.push_str("  services:\n");
                for svc in services {
                    out.push_str(&format!("    - name: {}\n", svc.name));
                    if let Some(ref alias) = svc.alias {
                        out.push_str(&format!("      alias: {alias}\n"));
                    }
                }
            }
            if let Some(parallel) = job.parallel {
                out.push_str(&format!("  parallel: {parallel}\n"));
            }
            if let Some(allow_failure) = job.allow_failure {
                out.push_str(&format!("  allow_failure: {allow_failure}\n"));
            }
            if let Some(ref when) = job.when {
                out.push_str(&format!("  when: {when}\n"));
            }
            if let Some(retry) = job.retry {
                out.push_str(&format!("  retry: {retry}\n"));
            }
            if let Some(ref timeout) = job.timeout {
                out.push_str(&format!("  timeout: {timeout}\n"));
            }
            if let Some(ref tags) = job.tags {
                out.push_str(&format!("  tags: {}\n", yaml_gitlab_list(tags)));
            }
            if let Some(ref artifacts) = job.artifacts {
                out.push_str("  artifacts:\n");
                out.push_str(&format!("    expire_in: {}\n", artifacts.expire_in));
                if !artifacts.paths.is_empty() {
                    out.push_str("    paths:\n");
                    for p in &artifacts.paths {
                        out.push_str(&format!("      - {p}\n"));
                    }
                }
            }
            out.push_str("  script:\n");
            for s in &job.script {
                out.push_str(&format!("    - {s}\n"));
            }
            out.push('\n');
        }
        out
    }

    pub fn generate<R: AsRef<Path>>(output_dir: R) -> Result<(), String> {
        let config = Self::generate_gitlab_ci();
        let yaml = config.to_yaml();
        fs::write(output_dir.as_ref().join(".gitlab-ci.yml"), &yaml)
            .map_err(|e| format!("Cannot write .gitlab-ci.yml: {e}"))
    }

    pub fn generate_gitlab_ci() -> Self {
        let mut config = Self::new();

        config.jobs.insert(
            "test-cargo".into(),
            GitLabJob {
                stage: "test".into(),
                image: None,
                needs: vec![],
                script: vec![
                    "cargo check --all-targets".into(),
                    "cargo clippy --all-targets -- -D warnings".into(),
                    "cargo fmt --check".into(),
                    "cargo test --all-targets".into(),
                ],
                only: None,
                except: None,
                variables: None,
                artifacts: None,
                cache: None,
                environment: None,
                services: None,
                parallel: None,
                allow_failure: None,
                when: None,
                retry: None,
                timeout: None,
                tags: None,
            },
        );

        config.jobs.insert(
            "build-release".into(),
            GitLabJob {
                stage: "build".into(),
                image: None,
                needs: vec!["test-cargo".into()],
                script: vec!["cargo build --release --locked".into()],
                only: Some(HashMap::from([("refs".into(), vec!["main".into(), "master".into(), "tags".into()])])),
                except: None,
                variables: None,
                artifacts: Some(GitLabArtifacts {
                    paths: vec!["target/release/klyron".into()],
                    expire_in: "1 week".into(),
                    reports: None,
                }),
                cache: None,
                environment: None,
                services: None,
                parallel: None,
                allow_failure: None,
                when: None,
                retry: None,
                timeout: None,
                tags: None,
            },
        );

        config.jobs.insert(
            "docker-build".into(),
            GitLabJob {
                stage: "docker".into(),
                image: Some("docker:latest".into()),
                needs: vec!["build-release".into()],
                script: vec![
                    "docker build -f deploy/docker/Dockerfile.multi -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .".into(),
                    "docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest".into(),
                    "docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA".into(),
                    "docker push $CI_REGISTRY_IMAGE:latest".into(),
                ],
                only: Some(HashMap::from([("refs".into(), vec!["main".into(), "master".into()])])),
                except: None,
                variables: None,
                artifacts: None,
                cache: None,
                environment: None,
                services: Some(vec![GitLabService {
                    name: "docker:dind".into(),
                    alias: Some("docker".into()),
                    entrypoint: None,
                    command: None,
                }]),
                parallel: None,
                allow_failure: None,
                when: None,
                retry: None,
                timeout: None,
                tags: None,
            },
        );

        let environments = vec!["dev", "staging", "prod"];
        for env in &environments {
            config.jobs.insert(
                format!("deploy-{env}"),
                GitLabJob {
                    stage: "deploy".into(),
                    image: None,
                    needs: vec!["docker-build".into()],
                    script: vec![
                        format!("echo \"Deploying to {env}...\""),
                        format!("cargo run -- deploy --env {env}"),
                    ],
                    only: Some(HashMap::from([("refs".into(), vec!["main".into(), "master".into()])])),
                    except: None,
                    variables: None,
                    artifacts: None,
                    cache: None,
                    environment: Some(GitLabEnvironment {
                        name: env.to_string(),
                        url: format!("https://klyron-{env}.example.com"),
                        on_stop: None,
                        action: Some("start".into()),
                    }),
                    services: None,
                    parallel: None,
                    allow_failure: None,
                    when: Some("manual".into()),
                    retry: None,
                    timeout: Some("30m".into()),
                    tags: None,
                },
            );
        }

        config
    }
}

fn yaml_gitlab_list(items: &[String]) -> String {
    let vals: Vec<String> = items.iter().map(|s| format!("'{s}'")).collect();
    format!("[{}]", vals.join(", "))
}
