use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JenkinsPipeline {
    pub agents: JenkinsAgent,
    pub stages: Vec<JenkinsStage>,
    pub post: JenkinsPost,
    pub environment: HashMap<String, String>,
    pub tools: HashMap<String, String>,
    pub options: Vec<String>,
    pub triggers: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JenkinsAgent {
    pub label: String,
    pub docker_image: Option<String>,
    pub docker_args: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JenkinsStage {
    pub name: String,
    pub agent: Option<JenkinsAgent>,
    pub when: Option<String>,
    pub parallel: Option<HashMap<String, JenkinsParallelBranch>>,
    pub steps: Vec<String>,
    pub post: Option<JenkinsPost>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JenkinsParallelBranch {
    pub steps: Vec<String>,
    pub agent: Option<JenkinsAgent>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JenkinsPost {
    pub always: Vec<String>,
    pub success: Vec<String>,
    pub failure: Vec<String>,
    pub unstable: Vec<String>,
    pub changed: Vec<String>,
}

impl JenkinsPipeline {
    pub fn new() -> Self {
        Self {
            agents: JenkinsAgent {
                label: "linux".into(),
                docker_image: Some("rust:latest".into()),
                docker_args: Some("-v /var/run/docker.sock:/var/run/docker.sock".into()),
            },
            stages: Vec::new(),
            post: JenkinsPost {
                always: vec![],
                success: vec![],
                failure: vec![],
                unstable: vec![],
                changed: vec![],
            },
            environment: HashMap::from([
                ("CARGO_TERM_COLOR".into(), "always".into()),
                ("RUSTFLAGS".into(), "-D warnings".into()),
            ]),
            tools: HashMap::new(),
            options: vec!["timestamps()".into(), "ansiColor('xterm')".into(), "skipDefaultCheckout()".into()],
            triggers: vec![],
        }
    }

    pub fn generate(&self) -> String {
        let mut out = String::from("// Klyron Jenkins Pipeline\n// Generated by klyron_deploy_system\n\npipeline {\n");
        out.push_str("  agent any\n\n");

        if !self.tools.is_empty() {
            out.push_str("  tools {\n");
            for (name, version) in &self.tools {
                out.push_str(&format!("    {name} '{version}'\n"));
            }
            out.push_str("  }\n\n");
        }

        if !self.options.is_empty() {
            out.push_str("  options {\n");
            for opt in &self.options {
                out.push_str(&format!("    {opt}\n"));
            }
            out.push_str("  }\n\n");
        }

        if !self.triggers.is_empty() {
            out.push_str("  triggers {\n");
            for trigger in &self.triggers {
                out.push_str(&format!("    {trigger}\n"));
            }
            out.push_str("  }\n\n");
        }

        if !self.environment.is_empty() {
            out.push_str("  environment {\n");
            for (k, v) in &self.environment {
                out.push_str(&format!("    {k} = '{v}'\n"));
            }
            out.push_str("  }\n\n");
        }

        out.push_str("  stages {\n");
        for stage in &self.stages {
            out.push_str(&format!("    stage('{}') {{\n", stage.name));
            if let Some(ref agent) = stage.agent {
                if let Some(ref img) = agent.docker_image {
                    out.push_str(&format!("      agent {{ docker {img} }}\n"));
                }
            }
            if let Some(ref when) = stage.when {
                out.push_str(&format!("      when {{ {when} }}\n"));
            }
            if let Some(ref parallel) = stage.parallel {
                out.push_str("      parallel {\n");
                for (name, branch) in parallel {
                    out.push_str(&format!("        stage('{name}') {{\n"));
                    if let Some(ref agent) = branch.agent {
                        if let Some(ref img) = agent.docker_image {
                            out.push_str(&format!("          agent {{ docker {img} }}\n"));
                        }
                    }
                    out.push_str("          steps {\n");
                    for step in &branch.steps {
                        out.push_str(&format!("            {step}\n"));
                    }
                    out.push_str("          }\n");
                    out.push_str("        }\n");
                }
                out.push_str("      }\n");
            }
            out.push_str("      steps {\n");
            for step in &stage.steps {
                out.push_str(&format!("        {step}\n"));
            }
            out.push_str("      }\n");

            if let Some(ref post) = stage.post {
                out.push_str(&format!("      post {{\n"));
                Self::write_post_section(&mut out, post);
                out.push_str(&format!("      }}\n"));
            }

            out.push_str("    }\n\n");
        }
        out.push_str("  }\n\n");

        out.push_str("  post {\n");
        Self::write_post_section(&mut out, &self.post);
        out.push_str("  }\n");
        out.push_str("}\n");
        out
    }

    fn write_post_section(out: &mut String, post: &JenkinsPost) {
        if !post.always.is_empty() {
            out.push_str("    always {\n");
            for s in &post.always {
                out.push_str(&format!("      {s}\n"));
            }
            out.push_str("    }\n");
        }
        if !post.success.is_empty() {
            out.push_str("    success {\n");
            for s in &post.success {
                out.push_str(&format!("      {s}\n"));
            }
            out.push_str("    }\n");
        }
        if !post.failure.is_empty() {
            out.push_str("    failure {\n");
            for s in &post.failure {
                out.push_str(&format!("      {s}\n"));
            }
            out.push_str("    }\n");
        }
        if !post.unstable.is_empty() {
            out.push_str("    unstable {\n");
            for s in &post.unstable {
                out.push_str(&format!("      {s}\n"));
            }
            out.push_str("    }\n");
        }
        if !post.changed.is_empty() {
            out.push_str("    changed {\n");
            for s in &post.changed {
                out.push_str(&format!("      {s}\n"));
            }
            out.push_str("    }\n");
        }
    }

    pub fn generate_jenkinsfile() -> Self {
        let mut pipeline = Self::new();
        pipeline.tools.insert("rust".into(), "stable".into());
        pipeline.triggers.push("cron('H H * * *')".into());
        pipeline.triggers.push("pollSCM('H/15 * * * *')".into());

        pipeline.stages.push(JenkinsStage {
            name: "Checkout".into(),
            agent: None,
            when: None,
            parallel: None,
            steps: vec!["checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/klyron/klyron.git']])".into()],
            post: None,
        });

        pipeline.stages.push(JenkinsStage {
            name: "Build & Test".into(),
            agent: None,
            when: None,
            parallel: Some(HashMap::from([
                (
                    "cargo-check".into(),
                    JenkinsParallelBranch {
                        steps: vec!["sh 'cargo check --all-targets'".into()],
                        agent: None,
                    },
                ),
                (
                    "cargo-clippy".into(),
                    JenkinsParallelBranch {
                        steps: vec!["sh 'cargo clippy --all-targets -- -D warnings'".into()],
                        agent: None,
                    },
                ),
                (
                    "cargo-test".into(),
                    JenkinsParallelBranch {
                        steps: vec!["sh 'cargo test --all-targets'".into()],
                        agent: None,
                    },
                ),
            ])),
            steps: vec![],
            post: Some(JenkinsPost {
                always: vec!["junit 'target/nextest/default/junit.xml'".into()],
                success: vec![],
                failure: vec![],
                unstable: vec![],
                changed: vec![],
            }),
        });

        pipeline.stages.push(JenkinsStage {
            name: "Build Release".into(),
            agent: None,
            when: Some("branch 'main' || branch 'master'".into()),
            parallel: None,
            steps: vec![
                "stash name: 'cargo-registry', includes: '~/.cargo/registry/**'".into(),
                "sh 'cargo build --release --locked'".into(),
                "stash name: 'release-binary', includes: 'target/release/klyron'".into(),
            ],
            post: None,
        });

        pipeline.stages.push(JenkinsStage {
            name: "Docker Build".into(),
            agent: Some(JenkinsAgent {
                label: "linux".into(),
                docker_image: Some("docker:latest".into()),
                docker_args: None,
            }),
            when: Some("branch 'main' || branch 'master'".into()),
            parallel: None,
            steps: vec![
                "unstash 'release-binary'".into(),
                "sh 'docker build -f deploy/docker/Dockerfile.multi -t ghcr.io/klyron/klyron:latest .'".into(),
                "withCredentials([string(credentialsId: 'ghcr-token', variable: 'GHCR_TOKEN')]) { sh 'echo $GHCR_TOKEN | docker login ghcr.io -u klyron --password-stdin' }".into(),
                "sh 'docker push ghcr.io/klyron/klyron:latest'".into(),
            ],
            post: None,
        });

        pipeline.stages.push(JenkinsStage {
            name: "Deploy".into(),
            agent: None,
            when: Some("branch 'main' || branch 'master'".into()),
            parallel: None,
            steps: vec![
                "unstash 'release-binary'".into(),
                "sh 'cargo run -- deploy --env production'".into(),
            ],
            post: Some(JenkinsPost {
                always: vec![],
                success: vec!["emailext(to: 'team@klyron.dev', subject: 'Deploy successful', body: 'Deployment to production completed successfully.')".into()],
                failure: vec!["emailext(to: 'team@klyron.dev', subject: 'Deploy FAILED', body: 'Deployment to production failed. Please check the logs.')".into()],
                unstable: vec![],
                changed: vec![],
            }),
        });

        pipeline.post = JenkinsPost {
            always: vec![
                "archiveArtifacts artifacts: 'target/release/klyron', fingerprint: true".into(),
                "cleanWs()".into(),
            ],
            success: vec!["echo 'Pipeline completed successfully'".into()],
            failure: vec!["echo 'Pipeline failed'".into()],
            unstable: vec!["echo 'Pipeline is unstable'".into()],
            changed: vec!["echo 'Pipeline state changed'".into()],
        };

        pipeline
    }

    pub fn write<R: AsRef<Path>>(output_dir: R) -> Result<(), String> {
        let pipeline = Self::generate_jenkinsfile();
        let groovy = pipeline.generate();
        fs::write(output_dir.as_ref().join("Jenkinsfile"), &groovy)
            .map_err(|e| format!("Cannot write Jenkinsfile: {e}"))
    }
}

impl Default for JenkinsPipeline {
    fn default() -> Self {
        Self::new()
    }
}
