use super::{CloudDeploy, CloudDeployConfig, DeployResult, DeployState, DeployStatus, validate_common_config};
use std::time::Duration;

pub struct CloudflareDeployer {
    pub account_id: String,
    pub zone_id: String,
    pub workers_dev: bool,
    pub route: Option<String>,
}

impl CloudflareDeployer {
    pub fn new(account_id: &str, zone_id: &str) -> Self {
        Self {
            account_id: account_id.to_string(),
            zone_id: zone_id.to_string(),
            workers_dev: true,
            route: None,
        }
    }

    pub fn with_route(mut self, route: &str) -> Self {
        self.workers_dev = false;
        self.route = Some(route.to_string());
        self
    }

    fn generate_wrangler_toml(&self, config: &CloudDeployConfig) -> String {
        let route_section = if let Some(ref route) = self.route {
            format!(
                r#"
routes = [
  {{ pattern = "{route}", zone_id = "{zone}" }},
]
"#,
                route = route,
                zone = self.zone_id,
            )
        } else {
            String::new()
        };

        let env_vars: String = config.env_vars.iter()
            .map(|(k, v)| format!("{k} = \"{v}\""))
            .collect::<Vec<_>>()
            .join("\n");

        let secrets: String = config.secrets.iter()
            .map(|s| format!("{s} = \"\""))
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            r#"# Generated by Klyron Deploy
name = "{name}"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "{account}"
workers_dev = {workers_dev}
{route_section}
[build]
command = "npm run build"
upload = {{ format = "service-worker" }}

[env.{env_name}]
{env_vars}

[secrets]
{secrets}

[triggers]
crons = []

[durable_objects]
bindings = []

[[migrations]]
tag = "v1"
new_classes = []

[logpush]
enable = false
"#,
            name = config.project_name,
            account = self.account_id,
            workers_dev = if self.workers_dev { "true" } else { "false" },
            route_section = route_section,
            env_name = config.environment,
            env_vars = env_vars,
            secrets = secrets,
        )
    }
}

impl CloudDeploy for CloudflareDeployer {
    fn validate_config(&self, config: &CloudDeployConfig) -> anyhow::Result<()> {
        validate_common_config(config)?;
        if self.account_id.is_empty() {
            anyhow::bail!("account_id is required for Cloudflare deployment");
        }
        Ok(())
    }

    fn deploy(&self, config: &CloudDeployConfig) -> anyhow::Result<DeployResult> {
        self.validate_config(config)?;
        let deploy_id = uuid::Uuid::new_v4().to_string();
        let wrangler_toml = self.generate_wrangler_toml(config);
        let out_dir = std::path::PathBuf::from(&config.project_name);
        std::fs::create_dir_all(&out_dir)?;
        std::fs::write(out_dir.join("wrangler.toml"), &wrangler_toml)?;
        let worker_url = if self.workers_dev {
            format!("https://{}.{}.workers.dev", config.project_name, self.account_id)
        } else {
            self.route.clone().unwrap_or_default()
        };
        Ok(DeployResult {
            success: true,
            url: Some(worker_url),
            version: Some("latest".into()),
            deploy_id,
            logs: vec![format!("Generated wrangler.toml for Worker {}", config.project_name)],
            duration_ms: 0,
        })
    }

    fn rollback(&self, deploy_id: &str) -> anyhow::Result<DeployResult> {
        Ok(DeployResult {
            success: true,
            url: None,
            version: Some(deploy_id.to_string()),
            deploy_id: uuid::Uuid::new_v4().to_string(),
            logs: vec![format!("Rolled back Cloudflare Workers deployment {deploy_id}")],
            duration_ms: 0,
        })
    }

    fn get_status(&self, _deploy_id: &str) -> anyhow::Result<DeployStatus> {
        Ok(DeployStatus {
            state: DeployState::Healthy,
            message: "Cloudflare Worker is deployed".into(),
            progress: 100,
            started_at: chrono::Utc::now().to_rfc3339(),
            updated_at: chrono::Utc::now().to_rfc3339(),
        })
    }

    fn get_logs(&self, _deploy_id: &str, _since: Option<Duration>) -> anyhow::Result<Vec<String>> {
        Ok(vec![format!("https://dash.cloudflare.com/{}/workers/services/view/{}",
            self.account_id, "app")])
    }

    fn get_url(&self, _deploy_id: &str) -> anyhow::Result<String> {
        Ok(format!("https://{}.{}.workers.dev", "app", self.account_id))
    }
}
