import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Klyron',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="border-b">
          <nav className="max-w-6xl mx-auto px-4 py-4 flex items-center gap-6">
            <a href="/" className="font-bold text-xl">My App</a>
          </nav>
        </header>
        <main className="max-w-6xl mx-auto px-4 py-8">
          {children}
        </main>
        <footer className="border-t py-8 text-center text-sm text-gray-500">
          &copy; {new Date().getFullYear()} My App
        </footer>
      </body>
    </html>
  )
}
