import { readFileSync, statSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'

export function createAdapter() {
  return {
    name: 'next',
    detect(dir) {
      return existsSync(join(dir, 'next.config.ts')) || existsSync(join(dir, 'next.config.js')) || existsSync(join(dir, 'next.config.mjs'))
    },
    supportedVersions: ['14.0', '15.0', '15.1', '15.2', '15.3'],
    defaultVersion: '15.3',
    kind: 'Fullstack',

    async dev(dir, port) {
      const { spawn } = await import('child_process')
      const proc = spawn('npx', ['next', 'dev'], {
        cwd: dir,
        env: { ...process.env, PORT: String(port || 3000), NEXT_TELEMETRY_DISABLED: '1' },
        stdio: 'inherit'
      })
      return new Promise((resolve, reject) => {
        proc.on('close', (code) => code === 0 ? resolve() : reject(new Error(`Dev server exited with code ${code}`)))
      })
    },

    async build(dir) {
      const { execFile } = await import('child_process')
      await execFile('npx', ['next', 'build'], { cwd: dir })
    },

    async test(dir) {
      const { execFile } = await import('child_process')
      await execFile('npx', ['vitest', 'run'], { cwd: dir })
    },

    async lint(dir) {
      const { execFile } = await import('child_process')
      await execFile('npx', ['next', 'lint'], { cwd: dir })
    },

    async format(dir, writeMode) {
      const { execFile } = await import('child_process')
      await execFile('npx', writeMode ? ['prettier', '--write', '.'] : ['prettier', '--check', '.'], { cwd: dir })
    },

    scaffold(name, options) {
      return scaffoldNext(name, options)
    }
  }
}

function existsSync(p) {
  try { return statSync(p).isFile() } catch { return false }
}

async function scaffoldNext(name, options) {
  const projectDir = join(options.dir || process.cwd(), name)
  mkdirSync(join(projectDir, 'app'), { recursive: true })
  mkdirSync(join(projectDir, 'public'), { recursive: true })
  mkdirSync(join(projectDir, 'components'), { recursive: true })
  mkdirSync(join(projectDir, 'lib'), { recursive: true })
  mkdirSync(join(projectDir, 'styles'), { recursive: true })
  mkdirSync(join(projectDir, 'types'), { recursive: true })

  writeFileSync(join(projectDir, 'package.json'), JSON.stringify({
    name, version: '1.0.0', private: true,
    scripts: { dev: 'next dev', build: 'next build', start: 'next start', lint: 'next lint', format: 'prettier --write .', test: 'vitest run' },
    dependencies: { next: '^15.3.0', react: '^19.1.0', 'react-dom': '^19.1.0' },
    devDependencies: {
      typescript: '^5.7.0', '@types/node': '^22.13.0', '@types/react': '^19.1.0', '@types/react-dom': '^19.1.0',
      tailwindcss: '^4.0.0', postcss: '^8.5.0', autoprefixer: '^10.4.20',
      eslint: '^9.20.0', 'eslint-config-next': '^15.3.0', prettier: '^3.5.0', vitest: '^3.0.0'
    }
  }, null, 2))

  writeFileSync(join(projectDir, 'tsconfig.json'), JSON.stringify({
    compilerOptions: {
      target: 'ES2017', lib: ['dom', 'dom.iterable', 'esnext'], allowJs: true, skipLibCheck: true,
      strict: true, noEmit: true, esModuleInterop: true, module: 'esnext',
      moduleResolution: 'bundler', resolveJsonModule: true, isolatedModules: true,
      jsx: 'preserve', incremental: true, plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] }
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules']
  }, null, 2))

  writeFileSync(join(projectDir, 'next.config.ts'), `import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  experimental: { serverActions: true }
}

export default nextConfig
`)

  writeFileSync(join(projectDir, 'app', 'layout.tsx'), `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '${name}',
  description: 'Generated by Klyron'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`)

  writeFileSync(join(projectDir, 'app', 'page.tsx'), `export default function Home() {
  return (
    <main>
      <h1>Welcome to ${name}</h1>
    </main>
  )
}
`)

  writeFileSync(join(projectDir, 'app', 'globals.css'), '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n:root { --foreground: #000; --background: #fff; }\n')
  writeFileSync(join(projectDir, 'app', 'not-found.tsx'), `export default function NotFound() {
  return <div><h1>404 - Page Not Found</h1></div>
}
`)
  writeFileSync(join(projectDir, 'app', 'error.tsx'), `"use client"
export default function Error({ error, reset }: { error: Error & { digest?: string }; reset: () => void }) {
  return (
    <div>
      <h2>Something went wrong!</h2>
      <button onClick={() => reset()}>Try again</button>
    </div>
  )
}
`)
  writeFileSync(join(projectDir, 'app', 'loading.tsx'), `export default function Loading() {
  return <div>Loading...</div>
}
`)
  writeFileSync(join(projectDir, 'next-env.d.ts'), '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n')
  writeFileSync(join(projectDir, '.gitignore'), 'node_modules\n.next\n*.tsbuildinfo\n.DS_Store\n')
  writeFileSync(join(projectDir, '.prettierrc'), JSON.stringify({ semi: false, singleQuote: true, tabWidth: 2, trailingComma: 'es5', printWidth: 100 }))
  writeFileSync(join(projectDir, 'README.md'), `# ${name}\n\nNext.js App Router\n\nnpm run dev\n`)
}
