name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: cargo
      - uses: Swatinem/rust-cache@v2
      - name: Install tools
        run: |
          cargo install criterion-table hyperfine
      - name: Run benchmarks
        run: cargo bench -p klyron_bench -- --output-format bencher | tee output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: cargo
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: 200%
          comment-on-pr: true
          fail-on-alert: true
          benchmark-data-dir-path: dev/bench
