use crate::{LockfileV3, LockfilePackage, PmError};
use std::collections::{BTreeMap, HashMap};

/// Parse a yarn.lock v1 file into our LockfileV3 format
pub fn parse_yarn_lock(content: &str) -> Result<LockfileV3, PmError> {
    let mut packages = BTreeMap::new();

    let blocks: Vec<&str> = content
        .split("\n\n")
        .filter(|b| !b.trim().is_empty() && !b.trim().starts_with('#'))
        .collect();

    for block in blocks {
        let lines: Vec<&str> = block.lines().collect();
        if lines.is_empty() {
            continue;
        }

        let spec_line = lines[0].trim();
        if spec_line.is_empty() || !spec_line.ends_with(':') {
            continue;
        }
        let specifiers: Vec<&str> = spec_line
            .trim_end_matches(':')
            .split(',')
            .map(|s| s.trim().trim_matches('"'))
            .collect();

        if specifiers.is_empty() {
            continue;
        }

        let first_spec = specifiers[0];
        let name = first_spec.split('@')
            .next()
            .unwrap_or(first_spec)
            .trim();
        if name.is_empty() {
            continue;
        }

        let mut version = String::new();
        let mut resolved = None;
        let mut integrity = None;
        let mut dependencies: Option<HashMap<String, String>> = None;

        for line in &lines[1..] {
            let trimmed = line.trim();
            if trimmed.is_empty() {
                continue;
            }

            if let Some(val) = trimmed.strip_prefix("version ") {
                version = val.trim().trim_matches('"').to_string();
            } else if let Some(val) = trimmed.strip_prefix("resolved ") {
                resolved = Some(val.trim().trim_matches('"').to_string());
            } else if let Some(val) = trimmed.strip_prefix("integrity ") {
                integrity = Some(val.trim().trim_matches('"').to_string());
            } else if trimmed.starts_with("dependencies:") {
                let mut deps = HashMap::new();
                let base_indent = line.len() - line.trim_start().len();
                for dep_line in &lines[1..] {
                    let dep_trimmed = dep_line.trim();
                    let dep_indent = dep_line.len() - dep_line.trim_start().len();
                    if dep_indent > base_indent && dep_trimmed.contains('"') {
                        let parts: Vec<&str> = dep_trimmed.splitn(2, '"').collect();
                        if parts.len() >= 2 {
                            let dep_name = parts[0].trim().trim_end_matches(':');
                            let dep_ver = parts[1].trim_matches('"');
                            deps.insert(dep_name.to_string(), dep_ver.to_string());
                        }
                    }
                }
                dependencies = Some(deps);
            }
        }

        if !version.is_empty() {
            let node_modules_path = format!("node_modules/{}", name);
            let pkg = LockfilePackage {
                version: version.clone(),
                resolved,
                integrity,
                dependencies,
                optional_dependencies: None,
                peer_dependencies: None,
                dev: None,
                optional: None,
                bundled: None,
                engines: None,
                os: None,
                cpu: None,
                has_dev_dependencies: None,
            };
            packages.insert(node_modules_path, pkg);
        }
    }

    Ok(LockfileV3 {
        name: None,
        lockfile_version: Some("yarn-v1".to_string()),
        packages,
        workspaces: None,
        metadata: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_yarn_lock_basic() {
        let content = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

package-name@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/package-name/-/package-name-1.0.0.tgz#hash"
  integrity sha512-deadbeef
  dependencies:
    dep-name "^2.0.0"

dep-name@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/dep-name/-/dep-name-2.0.0.tgz#hash2"
  integrity sha512-abc123
"#;
        let lock = parse_yarn_lock(content).unwrap();
        assert_eq!(lock.packages.len(), 2);
        assert!(lock.packages.contains_key("node_modules/package-name"));
        assert!(lock.packages.contains_key("node_modules/dep-name"));
        assert_eq!(lock.packages["node_modules/package-name"].version, "1.0.0");
    }

    #[test]
    fn test_parse_yarn_lock_empty() {
        let content = "# yarn lockfile v1\n";
        let lock = parse_yarn_lock(content).unwrap();
        assert_eq!(lock.packages.len(), 0);
    }

    #[test]
    fn test_parse_yarn_lock_with_deps() {
        let content = r#"root@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/root/-/root-1.0.0.tgz#hash"
  integrity sha512-xyz
  dependencies:
    child "^0.5.0"

child@^0.5.0:
  version "0.5.0"
  resolved "https://registry.yarnpkg.com/child/-/child-0.5.0.tgz#hash2"
  integrity sha512-abc
"#;
        let lock = parse_yarn_lock(content).unwrap();
        let root = &lock.packages["node_modules/root"];
        let deps = root.dependencies.as_ref().unwrap();
        assert_eq!(deps.get("child").unwrap(), "^0.5.0");
    }
}
