use std::path::{Path, PathBuf};
use clap::Args;

#[derive(Args)]
pub struct ScaffoldArgs {
    pub name: String,
    #[arg(short, long, default_value = ".")]
    pub dir: PathBuf,
    #[arg(long)]
    pub version: Option<String>,
}

fn project_dir(args: &ScaffoldArgs) -> PathBuf {
    args.dir.join(&args.name)
}

fn write_files(base: &Path, files: Vec<(&str, &str)>) -> anyhow::Result<()> {
    for (name, content) in files {
        let path = base.join(name);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, content)?;
    }
    Ok(())
}

fn mkdirs(base: &Path, dirs: &[&str]) -> anyhow::Result<()> {
    for d in dirs {
        std::fs::create_dir_all(base.join(d))?;
    }
    Ok(())
}

pub fn scaffold_next(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["app", "app/api", "components", "lib", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "type-check": "tsc --noEmit",
    "format": "prettier --write .",
    "test": "vitest run"
  },
  "dependencies": { "next": "latest", "react": "latest", "react-dom": "latest" },
  "devDependencies": {
    "tailwindcss": "latest", "postcss": "latest", "autoprefixer": "latest",
    "eslint": "latest", "eslint-config-next": "latest", "prettier": "latest",
    "typescript": "latest", "@types/react": "latest", "@types/node": "latest",
    "vitest": "latest"
  }
}"#.replace("NAME", &args.name)),
        ("next.config.mjs", r#"const nextConfig = { reactStrictMode: true, images: { remotePatterns: [], formats: ["image/avif", "image/webp"] } }; export default nextConfig;"#),
        ("tsconfig.json", r#"{"compilerOptions": {"baseUrl": ".", "paths": { "@/*": ["./*"] }, "strict": true, "esModuleInterop": true, "skipLibCheck": true, "forceConsistentCasingInFileNames": true, "resolveJsonModule": true, "isolatedModules": true, "incremental": true, "module": "esnext", "moduleResolution": "bundler", "jsx": "preserve", "target": "es2017" }, "include": ["**/*.ts", "**/*.tsx"], "exclude": ["node_modules"] }"#),
        ("app/layout.tsx", r#"import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: { default: 'Next.js App', template: '%s | Next.js App' },
  description: 'Generated by klyron',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}"#),
        ("app/page.tsx", r#"export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Welcome to Next.js</h1>
    </main>
  )
}"#),
        ("app/globals.css", r#"@tailwind base;
@tailwind components;
@tailwind utilities;
"#),
        ("app/api/hello/route.ts", r#"import { NextResponse } from 'next/server'
export async function GET() { return NextResponse.json({ message: 'Hello from Next.js!' }) }"#),
        ("tailwind.config.ts", r#"import type { Config } from 'tailwindcss'
const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: { extend: {} },
  plugins: [],
}
export default config"#),
        ("postcss.config.js", r#"module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }"#),
        (".eslintrc.json", r#"{"extends": ["next/core-web-vitals"]}"#),
        (".prettierrc", r#"{"semi": false, "singleQuote": true, "tabWidth": 2, "trailingComma": "es5"}"#),
        (".gitignore", "node_modules\n.next\n.env\n*.local\n"),
        ("README.md", &format!("# {}\n\nGenerated by [Klyron](https://klyron.dev)\n\n```bash\nnpm run dev\n```\n", args.name)),
    ])?;
    println!("✅ Next.js app created: {}", pd.display());
    println!("  cd {} && npm install && npm run dev", pd.display());
    Ok(())
}

pub fn scaffold_react(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview", "lint": "eslint .", "format": "prettier --write .", "test": "vitest run" },
  "dependencies": { "react": "^19.0.0", "react-dom": "^19.0.0", "react-router-dom": "^7.0.0" },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0", "vite": "^6.0.0", "typescript": "^5.0.0",
    "@types/react": "^19.0.0", "@types/react-dom": "^19.0.0",
    "eslint": "^9.0.0", "@eslint/js": "^9.0.0", "prettier": "^3.0.0", "vitest": "^2.0.0"
  }
}"#.replace("NAME", &args.name)),
        ("vite.config.ts", r#"import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
export default defineConfig({ plugins: [react()] })"#),
        ("tsconfig.json", r#"{"compilerOptions": { "target": "ES2020", "useDefineForClassFields": true, "lib": ["ES2020", "DOM", "DOM.Iterable"], "module": "ESNext", "skipLibCheck": true, "moduleResolution": "bundler", "allowImportingTsExtensions": true, "isolatedModules": true, "moduleDetection": "force", "noEmit": true, "jsx": "react-jsx", "strict": true, "noUnusedLocals": true, "noUnusedParameters": true, "noFallthroughCasesInSwitch": true }, "include": ["src"] }"#),
        ("index.html", r#"<!doctype html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>React App</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>"#),
        ("src/main.tsx", r#"import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App.tsx'
import './index.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>
)"#),
        ("src/App.tsx", r#"import { Routes, Route } from 'react-router-dom'
import Home from './pages/Home'

function App() {
  return (
    <Routes>
      <Route path="/" element={<Home />} />
    </Routes>
  )
}
export default App"#),
        ("src/pages/Home.tsx", r#"export default function Home() {
  return <div><h1>Welcome to React!</h1></div>
}"#),
        ("src/index.css", r#"* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: system-ui, sans-serif; }"#),
        ("src/vite-env.d.ts", r#"/// <reference types="vite/client" />"#),
        (".gitignore", "node_modules\ndist\n.env\n"),
        ("README.md", &format!("# {}\n\nReact + Vite + TypeScript\nGenerated by Klyron\n", args.name)),
    ])?;
    println!("✅ React app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_vue(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "src/components", "src/pages", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview", "lint": "eslint .", "format": "prettier --write ." },
  "dependencies": { "vue": "^3.5.0", "vue-router": "^4.0.0", "pinia": "^2.0.0" },
  "devDependencies": { "@vitejs/plugin-vue": "^5.0.0", "vite": "^6.0.0", "typescript": "^5.0.0", "eslint": "^9.0.0", "prettier": "^3.0.0" }
}"#.replace("NAME", &args.name)),
        ("vite.config.ts", r#"import { defineConfig } from 'vite'; import vue from '@vitejs/plugin-vue'
export default defineConfig({ plugins: [vue()] })"#),
        ("src/App.vue", r#"<script setup lang="ts">
import { RouterView } from 'vue-router'
</script>
<template>
  <RouterView />
</template>"#),
        ("src/main.ts", r#"import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import router from './router'
import './style.css'

createApp(App).use(createPinia()).use(router).mount('#app')"#),
        ("src/router/index.ts", r#"import { createRouter, createWebHistory } from 'vue-router'
import Home from '../pages/Home.vue'

const routes = [
  { path: '/', name: 'Home', component: Home }
]
export default createRouter({ history: createWebHistory(), routes })"#),
        ("src/pages/Home.vue", r#"<script setup lang="ts">
</script>
<template>
  <div><h1>Welcome to Vue 3!</h1></div>
</template>"#),
        ("index.html", r#"<!doctype html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Vue App</title></head><body><div id="app"></div><script type="module" src="/src/main.ts"></script></body></html>"#),
        ("tsconfig.json", r#"{"compilerOptions": { "target": "ES2020", "useDefineForClassFields": true, "module": "ESNext", "lib": ["ES2020", "DOM", "DOM.Iterable"], "skipLibCheck": true, "moduleResolution": "bundler", "allowImportingTsExtensions": true, "isolatedModules": true, "moduleDetection": "force", "noEmit": true, "jsx": "preserve", "strict": true }, "include": ["src/**/*.ts", "src/**/*.vue"] }"#),
        ("src/style.css", r#"* { margin: 0; padding: 0; } body { font-family: system-ui; }"#),
        ("src/vite-env.d.ts", r#"/// <reference types="vite/client" />
declare module '*.vue' { import type { DefineComponent } from 'vue'; const component: DefineComponent<{}, {}, any>; export default component; }"#),
        ("env.d.ts", r#"/// <reference types="vite/client" />"#),
    ])?;
    println!("✅ Vue 3 app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_sveltekit(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src/routes", "src/lib", "static"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "vite dev", "build": "vite build", "preview": "vite preview", "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json", "lint": "eslint .", "format": "prettier --write ." },
  "dependencies": {},
  "devDependencies": { "@sveltejs/adapter-auto": "^4.0.0", "@sveltejs/kit": "^2.0.0", "@sveltejs/vite-plugin-svelte": "^4.0.0", "svelte": "^5.0.0", "svelte-check": "^4.0.0", "typescript": "^5.0.0", "vite": "^6.0.0", "eslint": "^9.0.0", "prettier": "^3.0.0", "prettier-plugin-svelte": "^3.0.0", "tailwindcss": "^4.0.0" }
}"#.replace("NAME", &args.name)),
        ("svelte.config.js", r#"import adapter from '@sveltejs/adapter-auto'
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte'
export default { kit: { adapter: adapter() }, preprocess: vitePreprocess() }"#),
        ("vite.config.ts", r#"import { sveltekit } from '@sveltejs/kit/vite'
import { defineConfig } from 'vite'
export default defineConfig({ plugins: [sveltekit()] })"#),
        ("tsconfig.json", r#"{"extends": "./.svelte-kit/tsconfig.json", "compilerOptions": { "allowJs": true, "checkJs": true, "esModuleInterop": true, "forceConsistentCasingInFileNames": true, "resolveJsonModule": true, "skipLibCheck": true, "sourceMap": true, "strict": true, "moduleResolution": "bundler" } }"#),
        ("src/app.html", r#"<!doctype html><html lang="en"><head><meta charset="utf-8" /><link rel="icon" href="%sveltekit.assets%/favicon.png" /><meta name="viewport" content="width=device-width, initial-scale=1" />%sveltekit.head%</head><body><div id="app">%sveltekit.body%</div></body></html>"#),
        ("src/routes/+layout.svelte", r#"<script lang="ts"> let { children } = $props() </script>
<div class="app"> {@render children()} </div>"#),
        ("src/routes/+page.svelte", r#"<script lang="ts"> let count = $state(0) </script>
<div><h1>Welcome to SvelteKit!</h1><button onclick={() => count++}>Count: {count}</button></div>"#),
        ("src/lib/index.ts", r#"export const greeting = 'Hello from SvelteKit!'"#),
        ("static/favicon.png", ""),
        ("package.json", ""), // placeholder, will be replaced
    ])?;
    println!("✅ SvelteKit app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_astro(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src/pages", "src/components", "src/content", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "astro dev", "build": "astro build", "preview": "astro preview", "astro": "astro" },
  "dependencies": {}, "devDependencies": { "astro": "^5.0.0" }
}"#.replace("NAME", &args.name)),
        ("astro.config.mjs", r#"import { defineConfig } from 'astro/config'
export default defineConfig({ output: 'static' })"#),
        ("tsconfig.json", r#"{"compilerOptions": { "target": "ES2022", "module": "ESNext", "moduleResolution": "bundler", "allowImportingTsExtensions": true, "isolatedModules": true, "noEmit": true, "strict": true, "baseUrl": ".", "paths": { "@/*": ["./src/*"] } }, "include": ["src/**/*"] }"#),
        ("src/pages/index.astro", r#"---
import Layout from '../layouts/Layout.astro'
---
<Layout title="Home">
  <main><h1>Welcome to Astro!</h1></main>
</Layout>"#),
        ("src/layouts/Layout.astro", r#"---
interface Props { title: string }
const { title } = Astro.props
---
<!doctype html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width" /><title>{title}</title></head><body><slot /></body></html>"#),
        ("src/components/Header.astro", r#"<header><nav><a href="/">Home</a></nav></header>"#),
        ("public/style.css", r#"* { margin: 0; padding: 0; box-sizing: border-box; } body { font-family: system-ui; }"#),
        (".gitignore", "node_modules\ndist\n.env\n"),
        ("README.md", &format!("# {}\n\nGenerated by Klyron\n", args.name)),
    ])?;
    println!("✅ Astro app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_nuxt(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["pages", "components", "layouts", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "nuxt dev", "build": "nuxt build", "generate": "nuxt generate", "preview": "nuxt preview", "lint": "eslint .", "format": "prettier --write ." },
  "dependencies": {}, "devDependencies": { "nuxt": "^3.15.0", "vite": "^6.0.0", "eslint": "^9.0.0", "prettier": "^3.0.0" }
}"#.replace("NAME", &args.name)),
        ("nuxt.config.ts", r#"export default defineNuxtConfig({ compatibilityDate: '2024-11-01', devtools: { enabled: true } })"#),
        ("tsconfig.json", r#"{"extends": "./.nuxt/tsconfig.json", "compilerOptions": { "strict": true } }"#),
        ("app.vue", r#"<template><div><NuxtLayout><NuxtPage /></NuxtLayout></div></template>"#),
        ("layouts/default.vue", r#"<template><div><header>Nuxt App</header><slot /><footer>Footer</footer></div></template>"#),
        ("pages/index.vue", r#"<template><div><h1>Welcome to Nuxt 3!</h1></div></template>"#),
    ])?;
    println!("✅ Nuxt 3 app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_remix(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["app/routes", "app/components", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "remix dev", "build": "remix build", "start": "remix-serve build/server/index.js", "lint": "eslint .", "format": "prettier --write ." },
  "dependencies": { "@remix-run/node": "^2.0.0", "@remix-run/react": "^2.0.0", "@remix-run/serve": "^2.0.0", "react": "^19.0.0", "react-dom": "^19.0.0", "isbot": "^5.0.0" },
  "devDependencies": { "@remix-run/dev": "^2.0.0", "typescript": "^5.0.0", "eslint": "^9.0.0", "prettier": "^3.0.0" }
}"#.replace("NAME", &args.name)),
        ("remix.config.js", r#"export default { ignoredRouteFiles: ['**/*.css'] }"#),
        ("vite.config.ts", r#"import { vitePlugin as remix } from '@remix-run/dev'
import { defineConfig } from 'vite'
export default defineConfig({ plugins: [remix()] })"#),
        ("tsconfig.json", r#"{"compilerOptions": { "target": "ES2022", "lib": ["ES2022", "DOM", "DOM.Iterable"], "module": "ESNext", "skipLibCheck": true, "moduleResolution": "bundler", "allowImportingTsExtensions": true, "isolatedModules": true, "moduleDetection": "force", "noEmit": true, "jsx": "react-jsx", "strict": true, "baseUrl": ".", "paths": { "~/*": ["./app/*"] } }, "include": ["app"] }"#),
        ("app/root.tsx", r#"import { Links, Meta, Outlet, Scripts, ScrollRestoration } from '@remix-run/react'
export function Layout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><head><meta charSet="utf-8" /><Meta /><Links /></head><body>{children}<ScrollRestoration /><Scripts /></body></html>
}
export default function App() { return <Outlet /> }"#),
        ("app/routes/_index.tsx", r#"import type { MetaFunction } from '@remix-run/node'
export const meta: MetaFunction = () => [{ title: 'Remix App' }]
export default function Index() { return <div><h1>Welcome to Remix!</h1></div> }"#),
    ])?;
    println!("✅ Remix app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_angular(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src/app", "src/environments", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true,
  "scripts": { "ng": "ng", "start": "ng serve", "build": "ng build", "watch": "ng build --watch --configuration development", "test": "ng test", "lint": "ng lint", "format": "prettier --write ." },
  "dependencies": { "@angular/animations": "^19.0.0", "@angular/common": "^19.0.0", "@angular/compiler": "^19.0.0", "@angular/core": "^19.0.0", "@angular/forms": "^19.0.0", "@angular/platform-browser": "^19.0.0", "@angular/platform-browser-dynamic": "^19.0.0", "@angular/router": "^19.0.0", "rxjs": "~7.8.0", "tslib": "^2.3.0", "zone.js": "~0.14.0" },
  "devDependencies": { "@angular-devkit/build-angular": "^19.0.0", "@angular/cli": "^19.0.0", "@angular/compiler-cli": "^19.0.0", "typescript": "~5.6.0", "prettier": "^3.0.0" }
}"#.replace("NAME", &args.name)),
        ("angular.json", r#"{"$schema":"./node_modules/@angular/cli/lib/config/schema.json","version":1,"newProjectRoot":"projects","projects":{"my-app":{"projectType":"application","schematics":{},"root":"","sourceRoot":"src","prefix":"app","architect":{"build":{"builder":"@angular-devkit/build-angular:application","options":{"outputPath":"dist","index":"src/index.html","browser":"src/main.ts","polyfills":["zone.js"],"tsConfig":"tsconfig.app.json","assets":["public","src/favicon.ico"],"styles":["src/styles.css"],"scripts":[]},"configurations":{"production":{"budgets":[{"type":"initial","maximumWarning":"500kb","maximumError":"1mb"}],"outputHashing":"all"},"development":{"optimization":false,"extractLicenses":false,"sourceMap":true}},"defaultConfiguration":"production"},"serve":{"builder":"@angular-devkit/build-angular:dev-server","configurations":{"production":{"buildTarget":"my-app:build:production"},"development":{"buildTarget":"my-app:build:development"}},"defaultConfiguration":"development"},"extract-i18n":{"builder":"@angular-devkit/build-angular:extract-i18n"},"test":{"builder":"@angular-devkit/build-angular:karma"}}}}}"#),
        ("tsconfig.json", r#"{"compileOnSave":false,"compilerOptions":{"baseUrl":".","outDir":"./dist/out-tsc","forceConsistentCasingInFileNames":true,"strict":true,"noImplicitOverride":true,"noPropertyAccessFromIndexSignature":true,"noImplicitReturns":true,"noFallthroughCasesInSwitch":true,"sourceMap":true,"declaration":false,"downlevelIteration":true,"experimentalDecorators":true,"moduleResolution":"bundler","importHelpers":true,"target":"ES2022","module":"ES2022","useDefineForClassFields":false,"lib":["ES2022","dom"]},"angularCompilerOptions":{"enableI18nLegacyMessageIdFormat":false,"strictInjectionParameters":true,"strictInputAccessModifiers":true,"strictTemplates":true}}"#),
        ("src/index.html", r#"<!doctype html><html lang="en"><head><meta charset="utf-8"><title>AngularApp</title><base href="/"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" type="image/x-icon" href="favicon.ico"></head><body><app-root></app-root></body></html>"#),
        ("src/main.ts", r#"import { bootstrapApplication } from '@angular/platform-browser'
import { appConfig } from './app/app.config'
import { AppComponent } from './app/app.component'
bootstrapApplication(AppComponent, appConfig).catch((err) => console.error(err))"#),
        ("src/app/app.component.ts", r#"import { Component } from '@angular/core'
import { RouterOutlet } from '@angular/router'
@Component({ selector: 'app-root', imports: [RouterOutlet], template: '<router-outlet />' })
export class AppComponent { title = 'angular-app' }"#),
        ("src/app/app.config.ts", r#"import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core'
import { provideRouter } from '@angular/router'
import { routes } from './app.routes'
export const appConfig: ApplicationConfig = {
  providers: [provideZoneChangeDetection({ eventCoalescing: true }), provideRouter(routes)]
}"#),
        ("src/app/app.routes.ts", r#"import { Routes } from '@angular/router'
export const routes: Routes = []"#),
        ("src/styles.css", r#"/* Global styles */"#),
    ])?;
    println!("✅ Angular app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_solid(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview", "lint": "eslint .", "format": "prettier --write ." },
  "dependencies": { "solid-js": "^1.9.0" },
  "devDependencies": { "vite": "^6.0.0", "vite-plugin-solid": "^2.0.0", "typescript": "^5.0.0", "eslint": "^9.0.0", "prettier": "^3.0.0" }
}"#.replace("NAME", &args.name)),
    ])?;
    println!("✅ SolidJS app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_qwik(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src/routes", "src/components"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "vite --mode ssr", "build": "qwik build", "preview": "qwik preview" },
  "dependencies": { "@builder.io/qwik": "^1.9.0", "@builder.io/qwik-city": "^1.9.0" },
  "devDependencies": { "vite": "^6.0.0", "typescript": "^5.0.0" }
}"#.replace("NAME", &args.name)),
    ])?;
    println!("✅ Qwik app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_preact(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview" },
  "dependencies": { "preact": "^10.0.0" },
  "devDependencies": { "@preact/preset-vite": "^2.0.0", "vite": "^6.0.0", "typescript": "^5.0.0" }
}"#.replace("NAME", &args.name)),
    ])?;
    println!("✅ Preact app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_lit(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview" },
  "dependencies": { "lit": "^3.0.0" },
  "devDependencies": { "vite": "^6.0.0", "typescript": "^5.0.0" }
}"#.replace("NAME", &args.name)),
    ])?;
    println!("✅ Lit app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_express(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "src/routes", "src/middleware"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "start": "node src/index.js", "dev": "node --watch src/index.js", "lint": "eslint .", "format": "prettier --write ." },
  "dependencies": { "express": "^4.21.0", "cors": "^2.8.5", "morgan": "^1.10.0", "helmet": "^8.0.0" },
  "devDependencies": { "eslint": "^9.0.0", "prettier": "^3.0.0" }
}"#.replace("NAME", &args.name)),
        ("src/index.js", r#"import express from 'express'
import cors from 'cors'
import morgan from 'morgan'
import helmet from 'helmet'
import mainRouter from './routes/index.js'

const app = express()
app.use(helmet())
app.use(cors())
app.use(morgan('dev'))
app.use(express.json())
app.use('/', mainRouter)

const PORT = process.env.PORT || 3000
app.listen(PORT, () => console.log(`Server running on http://localhost:${PORT}`))"#),
        ("src/routes/index.js", r#"import { Router } from 'express'
const router = Router()
router.get('/', (req, res) => { res.json({ message: 'Hello from Express!' }) })
export default router"#),
    ])?;
    println!("✅ Express app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_fastify(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "src/routes"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "start": "node src/index.js", "dev": "node --watch src/index.js" },
  "dependencies": { "fastify": "^5.0.0", "@fastify/cors": "^10.0.0", "@fastify/swagger": "^9.0.0" },
  "devDependencies": {}
}"#.replace("NAME", &args.name)),
    ])?;
    println!("✅ Fastify app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_nest(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "src/modules"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true,
  "scripts": { "start": "nest start", "dev": "nest start --watch", "build": "nest build", "format": "prettier --write \"src/**/*.ts\"", "lint": "eslint \"{src,test}/**/*.ts\"" },
  "dependencies": { "@nestjs/common": "^11.0.0", "@nestjs/core": "^11.0.0", "@nestjs/platform-express": "^11.0.0", "reflect-metadata": "^0.2.0", "rxjs": "^7.8.0" },
  "devDependencies": { "@nestjs/cli": "^11.0.0", "@nestjs/schematics": "^11.0.0", "typescript": "^5.6.0", "eslint": "^9.0.0", "prettier": "^3.0.0" }
}"#.replace("NAME", &args.name)),
    ])?;
    println!("✅ NestJS app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_hono(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "node --watch src/index.js", "start": "node src/index.js" },
  "dependencies": { "hono": "^4.6.0", "zod": "^3.23.0" },
  "devDependencies": {}
}"#.replace("NAME", &args.name)),
        ("src/index.js", r#"import { Hono } from 'hono'
const app = new Hono()
app.get('/', (c) => c.json({ message: 'Hello from Hono!' }))
export default app"#),
    ])?;
    println!("✅ Hono app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_koa(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "start": "node src/index.js", "dev": "node --watch src/index.js" },
  "dependencies": { "koa": "^2.15.0", "@koa/router": "^12.0.0", "koa-bodyparser": "^4.4.0" },
  "devDependencies": {}
}"#.replace("NAME", &args.name)),
        ("src/index.js", r#"import Koa from 'koa'
import Router from '@koa/router'
import bodyParser from 'koa-bodyparser'
const app = new Koa()
const router = new Router()
router.get('/', (ctx) => { ctx.body = { message: 'Hello from Koa!' } })
app.use(bodyParser()).use(router.routes()).listen(3000)"#),
    ])?;
    println!("✅ Koa app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_hapi(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "start": "node src/index.js", "dev": "node --watch src/index.js" },
  "dependencies": { "@hapi/hapi": "^21.0.0" },
  "devDependencies": {}
}"#.replace("NAME", &args.name)),
        ("src/index.js", r#"import Hapi from '@hapi/hapi'
async function start() {
  const server = Hapi.server({ port: 3000, host: 'localhost' })
  server.route({ method: 'GET', path: '/', handler: (req, h) => ({ message: 'Hello from Hapi!' }) })
  await server.start()
  console.log('Server running on http://localhost:3000')
}
start()"#),
    ])?;
    println!("✅ Hapi.js app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_adonis(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["app", "config", "start", "resources"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "node ace serve --watch", "build": "node ace build", "start": "node bin/server.js" },
  "dependencies": { "@adonisjs/core": "^6.0.0" },
  "devDependencies": {}
}"#.replace("NAME", &args.name)),
    ])?;
    println!("✅ AdonisJS app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_svelte(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview" },
  "dependencies": { "svelte": "^5.0.0" },
  "devDependencies": { "@sveltejs/vite-plugin-svelte": "^4.0.0", "vite": "^6.0.0", "typescript": "^5.0.0" }
}"#.replace("NAME", &args.name)),
    ])?;
    println!("✅ Svelte app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_tauri(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "src-tauri", "src-tauri/src", "public"])?;
    write_files(&pd, vec![
        ("package.json", &r#"{
  "name": "NAME", "version": "0.1.0", "private": true, "type": "module",
  "scripts": { "dev": "vite", "build": "vite build && tauri build", "preview": "vite preview", "tauri": "tauri" },
  "dependencies": { "@tauri-apps/api": "^2.0.0" },
  "devDependencies": { "@tauri-apps/cli": "^2.0.0", "vite": "^6.0.0", "typescript": "^5.0.0" }
}"#.replace("NAME", &args.name)),
        ("index.html", r#"<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><title>Tauri App</title></head><body><div id="app"></div><script type="module" src="/src/main.ts"></script></body></html>"#),
        ("src/main.ts", r##"import { invoke } from "@tauri-apps/api/core";
const app = document.querySelector<HTMLDivElement>("#app");
if (app) {
  app.innerHTML = `<h1>Tauri + Klyron</h1><button id="greet-btn">Greet</button>`;
  document.querySelector("#greet-btn")?.addEventListener("click", async () => {
    alert(await invoke("greet", { name: "Klyron" }));
  });
}"##),
        ("src/styles.css", r#":root { font-family: Inter, sans-serif; } body { margin: 0; padding: 2rem; }"#),
        ("src-tauri/Cargo.toml", r#"[package] name = "tauri-app" version = "0.1.0" edition = "2021"
[dependencies] tauri = { version = "2", features = [] } serde = { version = "1", features = ["derive"] } serde_json = "1"
[build-dependencies] tauri-build = { version = "2", features = [] }"#),
        ("src-tauri/src/lib.rs", r#"#[tauri::command] fn greet(name: &str) -> String { format!("Hello, {}!", name) }
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() { tauri::Builder::default().invoke_handler(tauri::generate_handler![greet]).run(tauri::generate_context!()).expect("error"); }"#),
        ("src-tauri/src/main.rs", r#"#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
fn main() { tauri_app::run(); }"#),
        ("src-tauri/tauri.conf.json", r#"{"productName":"tauri-app","version":"0.1.0","identifier":"com.tauri-app","build":{"beforeDevCommand":"npm run dev","devUrl":"http://localhost:5173","beforeBuildCommand":"npm run build","frontendDist":"../dist"},"app":{"windows":[{"title":"Tauri App","width":800,"height":600}]}}"#),
        ("src-tauri/build.rs", r#"fn main() { tauri_build::build(); }"#),
    ])?;
    println!("✅ Tauri app created: {}", pd.display());
    Ok(())
}

pub fn scaffold_leptos(args: &ScaffoldArgs) -> anyhow::Result<()> {
    let pd = project_dir(args);
    if pd.exists() { anyhow::bail!("Directory exists: {}", pd.display()); }
    mkdirs(&pd, &["src", "public"])?;
    write_files(&pd, vec![
        ("Cargo.toml", r#"[package] name = "leptos-app" version = "0.1.0" edition = "2021"
[dependencies] leptos = { version = "0.7", features = ["csr"] } console_log = "1" wasm-bindgen = "0.2"
[profile.release] codegen-units = 1 lto = true"#),
        ("index.html", r#"<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Leptos App</title></head><body></body></html>"#),
        ("src/main.rs", r#"use leptos::*;
fn main() { mount_to_body(|| view! { <h1>"Hello, Leptos!"</h1> }) }"#),
    ])?;
    println!("✅ Leptos app created: {}", pd.display());
    Ok(())
}
